site_name: BioData Club GitHub Pages Tutorial

theme: material

plugins:
    - search

docs_dir: docs

pages:
    - Lesson Plan: index.md
    - Workshop Logistics:  workshop_logistics.md
    - 1 - A Personal Website for Professional Outreach: lessons/1.md
    - 2 - Publishing a GitHub Page: lessons/2.md
    - 3 - The Magic of Markdown: lessons/3.md
    - 4 - Best Practices for Sharing Your Work: lessons/4.md
    - Tips & Tricks: tips-tricks.md

    - Extra Topics:
        - Adding a menu item: extra/add-menu.md
        - Aesthetics & Appearance: extra/aesthetics.md
        - Linking External Photos: extra/external-photos.md
        - Blog Posts: extra/blog-posts.md
        - Embedding Presentations: extra/presentations.md
        - Custom Themes: extra/themes.md
        - HTML in Markdown: extra/html-markdown.md
        - Updating Favorite Icon: extra/favicon.md
        - Using GitHub Desktop: extra/github-desktop.md

    - Glossary: glossary.md
